version: "3.9"
services:
  app:
    build: .
    container_name: app
    depends_on:
      - mysql
    ports:
      - "7777:8081"
    restart: on-failure
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    expose:
      - "6379"
      - "8001"
    depends_on:
      - mysql